Still not read the scrambled data
KrakensAUVs/KrakensGames pull request #12
Opened 2022-02-15 02:21 UTC by moohbr

2022-03-03 21:59 UTC, mauricioLeite requested changes

2022-03-03 21:59 UTC, mauricioLeite commented on LICENSE
> +Copyright (c) 2022 moohbr
Como está no repositório do projeto, deve-se manter o `Krakens AUVs` e atualizar o ano somente.

2022-03-03 21:59 UTC, mauricioLeite commented on app/app.py
> +from results import amount_test
A maioria dos arquivos já existentes no repositório foram deletados, é necessário atualizar a branch e organizar o local dos arquivos de acordos com os outros PRs.

2022-03-03 21:59 UTC, mauricioLeite commented on README.md
> +
O texto devia se manter o mesmo, já que é referenciando a todo o repositório, e não somente ao projeto de poo.

2022-03-04 02:19 UTC, moohbr commented on README.md
> +
No caso não tem. Deixo sem?

2022-03-04 02:20 UTC, moohbr commented on LICENSE
> +Copyright (c) 2022 moohbr
Corrigido.

2022-03-10 23:13 UTC, moohbr commented
Sem os arquivos, vou subir um novo.

2022-03-10 23:13 UTC, closed without merging